version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:16.13.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: Run tests
          command: npm run test
      - store_artifacts:
          path: coverage
      - run:
          name: Colect coverage badge
          command: npm run test:badges